version: "3.4"
services:
    angular:
        container_name: scaleo-angular
        build:
            context: .
            args:
            - NG_VERSION=${NG_VERSION}
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - 4200:4200
            - 9999:9999
        restart: unless-stopped
        stdin_open: true
        tty: true
    nginx-client:
        image: nginx:alpine
        container_name: scaleo-nginx-client
        volumes:
            - "./docker/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./:/var/www/html"
            - "./docker/data/logs/nginx/access.log:/var/logs/nginx/access.log"
            - "./docker/data/logs/nginx/error.log:/var/logs/nginx/error.log"
            - "./docker/etc/ssl:/etc/ssl/${NGINX_HOST_CLIENT}"
        ports:
            - "8888:443"
        environment:
            - NGINX_HOST_CLIENT=${NGINX_HOST_CLIENT}
        command: /bin/sh -c "envsubst '$$NGINX_HOST_CLIENT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
