export const AFFILIATE_ENDPOINTS = (): any => endpoints;

export const endpoints = {
    // Dashboard
    'dashboard-statistics-network-summary': '/affiliate/dashboard/statistics/network-summary',
    'dashboard-statistics-get-options': '/affiliate/dashboard/statistics/{optionsUrl}',
    'dashboard-statistics': '/affiliate/dashboard/statistics',
    'dashboard-statistics-top-affiliates': '/affiliate/dashboard/statistics/top-affiliates',
    'dashboard-statistics-top-offers': '/affiliate/dashboard/statistics/top-offers',
    'dashboard-counts-info': '/affiliate/dashboard/counts-info',
    'dashboard-pending-postbacks': '/affiliate/dashboard/pending-postbacks',
    'dashboard-performance': '/affiliate/dashboard/statistics/performance',
    'dashboard-promote-offer': '/affiliate/dashboard/offers-by-categories',
    'dashboard-balance': '/affiliate/billing/your-balance-for-dashboard',

    'platform-list': '/affiliate/lists',
    'platform-counts-info': '/affiliate/offers/counts-info',
    'payments-create': '/affiliate/payments',
    'payments-delete': '/affiliate/payments/{editId}',
    'payments-columns': '/affiliate/payments/get-options',
    'payments-list': '/affiliate/payments/index',
    'payments-update': '/affiliate/payments/{editId}',
    'payments-view': '/affiliate/payments/{editId}',
    'payments-export': '/payments/export',
    'postback-create': '/affiliate/postbacks',
    'postback-update': '/affiliate/postbacks/{postbackId}',
    'postback-delete': '/affiliate/postbacks/{postbackId}',
    'postbacks-list': '/affiliate/postbacks',
    'postback-view': '/affiliate/postbacks/{postbackId}',
    'postback-counts': '/affiliate/postbacks/counts-info',

    // Offers
    'offers-counts-info': '/affiliate/offers/{id}/counts-info',
    'offers-list': '/affiliate/offers',
    'offer-view': '/affiliate/offers/{id}',
    'offers-get-filter-info': '/affiliate/offers/get-filter-info',
    'offers-goals-get-filter-info': '/affiliate/offers/{offerId}/goals/get-filter-info',
    'dashboard-offers-requests': '/affiliate/dashboard/pending-requests',
    'offer-request': '/affiliate/offers-requests',
    'offers-goals-extended-filter-info': '/affiliate/goals/extended-filter-info',
    'offers-urls-extended-filter-info': '/affiliate/urls/extended-filter-info',
    'offers-creatives-extended-filter-info': '/affiliate/creatives/extended-filter-info',
    'offers-get-xml-feed-creative': '/affiliate/offers/{offerId}/xml-feed-creative/{creativeId}',
    'smart-link-list': '/affiliate/smart-links/index',
    'smart-links': '/affiliate/smart-links/get-filter-info',

    // Reports
    'reports-click-options': '/affiliate/reports/clicks/get-options',
    'reports-click': '/affiliate/reports/clicks',
    'reports-click-export': '/affiliate/reports/clicks/export',
    'reports-conversions-options': '/affiliate/reports/conversions/get-options',
    'reports-conversions': '/affiliate/reports/conversions',
    'reports-conversions-export': '/affiliate/reports/conversions/export',
    'reports-statistics-options': '/affiliate/reports/statistics/get-options',
    'reports-statistics-breakdowns': '/affiliate/reports/statistics/get-breakdowns',
    'reports-statistics': '/affiliate/reports/statistics',
    'activity-log': '/affiliate/administration/activity-log',
    'reports-statistics-export': '/affiliate/reports/export',
    'reports-clicks-log': '/affiliate/reports/invalid-clicks-log',
    'reports-clicks-log-options': '/affiliate/reports/invalid-clicks-log/get-options',
    'reports-affiliates-postbacks-log': '/affiliate/reports/postbacks-log',
    'reports-affiliates-postbacks-log-options': '/affiliate/reports/postbacks-log/get-options',
    referrals: '/affiliate/referrals',
    'reports-referrals': '/affiliate/reports/referrals',
    'reports-statistic-filters': '/affiliate/reports/statistics/get-filters',
    'reports-conversions-filters': '/affiliate/reports/conversions/get-filters',
    'reports-clicks-filters': '/affiliate/reports/clicks/get-filters',
    'reports-clicks-log-filters': '/affiliate/reports/invalid-clicks-log/get-filters',
    'reports-affiliate-postbacks-filters': '/affiliate/reports/postbacks-log/get-filters',
    'reports-invalid-clicks-log-export': '/affiliate/reports/invalid-clicks-log/export',
    'reports-affiliates-postbacks-log-export': '/affiliate/reports/postbacks-log/export',

    'billing-details': '/affiliate/billing/details',
    'payments-methods-list': '/affiliate/billing/payments-methods',
    'select-payment-methods': '/affiliate/billing/select-payment-method',
    'announcements-list': '/affiliate/dashboard/announcements',
    'announcements-count': '/affiliate/dashboard/announcements/counts',

    // Affiliates
    'affiliate-sources-extended-filter-info': '/affiliate/sources/extended-filter-info',

    // Billings
    'billing-affiliates-payments-methods': '/affiliate/billing/affiliates-payments-methods',
    'affiliate-billing-balance': '/affiliate/billing/affiliates/balances',
    'affiliate-billing-detail': '/affiliate/billing/affiliates',
    'billing-affiliates-payments-methods-supported-currencies':
        '/affiliate/billing/affiliates-payments-methods/supported-currencies/{currency}',
    'billing-invoices-list': '/affiliate/billing/invoices/index',
    'billing-invoices-options': '/affiliate/billing/invoices/get-options',
    'billing-invoices-export': '/affiliate/billing/invoices/export',
    'billing-invoice-download-pdf': '/affiliate/billing/invoices/{id}/download-pdf',
    'billing-invoice': '/affiliate/billing/invoices/{id}',
    'billing-invoice-download-selected-pdf': '/affiliate/billing/invoices/download-pdf-zip',
    'billing-affiliates-payments-methods-create': '/affiliate/billing/affiliates-payments-methods/create',
    'billing-affiliates-payments-methods-update': '/affiliate/billing/affiliates-payments-methods/view-update',
    'billing-affiliates-payments-methods-delete': '/affiliate/billing/affiliates-payments-methods/delete/{id}',
    'billing-invoice-delete-attachment': '/affiliate/billing/invoices/delete-attachment/{id}',
    'billing-change-upload-attachment': '/affiliate/billing/invoices/upload-attachment/{id}',
    'billing-invoice-get-filter-info': '/affiliate/billing/invoices/get-filter-info',
    'billing-invoice-get-approved-balance': '/affiliate/billing/affiliates/get-approved-balance',
    'billing-invoice-send-payment-request': '/affiliate/billing/invoices/send-payment-request'
};
