import { LeadsReceiveFieldsIdEnum, LeadsReceiveFieldsTranslateEnum } from '../../enums/platform-list';

export const LEADS_RECEIVE_FIELDS_TRANSLATE_MAP = Object.freeze({
    [LeadsReceiveFieldsIdEnum.Email]: LeadsReceiveFieldsTranslateEnum.Email,
    [LeadsReceiveFieldsIdEnum.Phone]: LeadsReceiveFieldsTranslateEnum.Phone,
    [LeadsReceiveFieldsIdEnum.FirstName]: LeadsReceiveFieldsTranslateEnum.FirstName,
    [LeadsReceiveFieldsIdEnum.LastName]: LeadsReceiveFieldsTranslateEnum.LastName,
    [LeadsReceiveFieldsIdEnum.Address]: LeadsReceiveFieldsTranslateEnum.Address,
    [LeadsReceiveFieldsIdEnum.City]: LeadsReceiveFieldsTranslateEnum.City,
    [LeadsReceiveFieldsIdEnum.Region]: LeadsReceiveFieldsTranslateEnum.Region,
    [LeadsReceiveFieldsIdEnum.Postcode]: LeadsReceiveFieldsTranslateEnum.Postcode,
    [LeadsReceiveFieldsIdEnum.Country]: LeadsReceiveFieldsTranslateEnum.Country,
    [LeadsReceiveFieldsIdEnum.IP]: LeadsReceiveFieldsTranslateEnum.IP,
    [LeadsReceiveFieldsIdEnum.Birthday]: LeadsReceiveFieldsTranslateEnum.Birthday,
    [LeadsReceiveFieldsIdEnum.Vertical]: LeadsReceiveFieldsTranslateEnum.Vertical,
    [LeadsReceiveFieldsIdEnum.AffiliateClickId]: LeadsReceiveFieldsTranslateEnum.AffiliateClickId,
    [LeadsReceiveFieldsIdEnum.SubId1]: LeadsReceiveFieldsTranslateEnum.SubId1,
    [LeadsReceiveFieldsIdEnum.SubId2]: LeadsReceiveFieldsTranslateEnum.SubId2,
    [LeadsReceiveFieldsIdEnum.SubId3]: LeadsReceiveFieldsTranslateEnum.SubId3,
    [LeadsReceiveFieldsIdEnum.SubId4]: LeadsReceiveFieldsTranslateEnum.SubId4,
    [LeadsReceiveFieldsIdEnum.SubId5]: LeadsReceiveFieldsTranslateEnum.SubId5,
    [LeadsReceiveFieldsIdEnum.CustomField1]: LeadsReceiveFieldsTranslateEnum.CustomField1,
    [LeadsReceiveFieldsIdEnum.CustomField2]: LeadsReceiveFieldsTranslateEnum.CustomField2,
    [LeadsReceiveFieldsIdEnum.CustomField3]: LeadsReceiveFieldsTranslateEnum.CustomField3,
    [LeadsReceiveFieldsIdEnum.CustomField4]: LeadsReceiveFieldsTranslateEnum.CustomField4,
    [LeadsReceiveFieldsIdEnum.CustomField5]: LeadsReceiveFieldsTranslateEnum.CustomField5,
    [LeadsReceiveFieldsIdEnum.CustomField6]: LeadsReceiveFieldsTranslateEnum.CustomField6,
    [LeadsReceiveFieldsIdEnum.CustomField7]: LeadsReceiveFieldsTranslateEnum.CustomField7,
    [LeadsReceiveFieldsIdEnum.CustomField8]: LeadsReceiveFieldsTranslateEnum.CustomField8,
    [LeadsReceiveFieldsIdEnum.CustomField9]: LeadsReceiveFieldsTranslateEnum.CustomField9,
    [LeadsReceiveFieldsIdEnum.CustomField10]: LeadsReceiveFieldsTranslateEnum.CustomField10,
    [LeadsReceiveFieldsIdEnum.CustomField11]: LeadsReceiveFieldsTranslateEnum.CustomField11,
    [LeadsReceiveFieldsIdEnum.CustomField12]: LeadsReceiveFieldsTranslateEnum.CustomField12,
    [LeadsReceiveFieldsIdEnum.CustomField13]: LeadsReceiveFieldsTranslateEnum.CustomField13,
    [LeadsReceiveFieldsIdEnum.CustomField14]: LeadsReceiveFieldsTranslateEnum.CustomField14,
    [LeadsReceiveFieldsIdEnum.CustomField15]: LeadsReceiveFieldsTranslateEnum.CustomField15,
    [LeadsReceiveFieldsIdEnum.CustomField16]: LeadsReceiveFieldsTranslateEnum.CustomField16,
    [LeadsReceiveFieldsIdEnum.CustomField17]: LeadsReceiveFieldsTranslateEnum.CustomField17,
    [LeadsReceiveFieldsIdEnum.CustomField18]: LeadsReceiveFieldsTranslateEnum.CustomField18,
    [LeadsReceiveFieldsIdEnum.CustomField19]: LeadsReceiveFieldsTranslateEnum.CustomField19,
    [LeadsReceiveFieldsIdEnum.CustomField120]: LeadsReceiveFieldsTranslateEnum.CustomField120
});
